### PR TITLE
moved to bigdata

### PR DESCRIPTION
**Pull request by antonkulaga**
Перевёл все на бигдату, все тесты успешно проходят

[Review on Reviewable](https://reviewable.io/reviews/denigma/plasmid-bank/19)

### CODE REVIEW

**Comment by rmihael** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[backend/src/main/scala/club/diybio/bank/domain/BananaPlasmidVectorRepository.scala, line 143 [r1]](https://reviewable.io:443/reviews/denigma/plasmid-bank/19#-JsU9AJbdVTZWwWlBLmT)** ([raw file](https://github.com/denigma/plasmid-bank/blob/cc896bd1822f29b9fb490e2469b3aa17370b9178/backend/src/main/scala/club/diybio/bank/domain/BananaPlasmidVectorRepository.scala#L143)):</sup>
Стрёмновато, что функция дёргается каждый раз. Неясна семантика повторных вызовов. Если под ней пул -- хорошо, а если каждый раз открывается новое соединение?

---

<sup>**[backend/src/main/scala/club/diybio/bank/domain/bank/BananaDepositorRepository.scala, line 13 [r1]](https://reviewable.io:443/reviews/denigma/plasmid-bank/19#-JsU9SKQ1UdYIj_3Nrkh)** ([raw file](https://github.com/denigma/plasmid-bank/blob/cc896bd1822f29b9fb490e2469b3aa17370b9178/backend/src/main/scala/club/diybio/bank/domain/bank/BananaDepositorRepository.scala#L13)):</sup>
Собственно ключевой вопрос: в чём в данном случае ценность передачи функции, а не объекта соединения?

---

<sup>**[backend/src/main/scala/club/diybio/bank/utils/sparql/QuerySyntax.scala, line 3 [r1]](https://reviewable.io:443/reviews/denigma/plasmid-bank/19#-JsU9nYfAJ0-UBJj5iP-)** ([raw file](https://github.com/denigma/plasmid-bank/blob/cc896bd1822f29b9fb490e2469b3aa17370b9178/backend/src/main/scala/club/diybio/bank/utils/sparql/QuerySyntax.scala#L3)):</sup>
Давай всю заготовку для DSL выкинем в какую-то отдельную ветку, что бы основной репоз не перегружала

---

<sup>**[project/Dependencies.scala, line 56 [r1]](https://reviewable.io:443/reviews/denigma/plasmid-bank/19#-JsUADVeQb_ap0xhiuzS)** ([raw file](https://github.com/denigma/plasmid-bank/blob/cc896bd1822f29b9fb490e2469b3aa17370b9178/project/Dependencies.scala#L56)):</sup>
А что делает этот excludeAll?

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/denigma/plasmid-bank/19)

**Comment by antonkulaga** [comment]
<sup>**[backend/src/main/scala/club/diybio/bank/domain/BananaPlasmidVectorRepository.scala, line 143 [r1]](https://reviewable.io:443/reviews/denigma/plasmid-bank/19#-JsU9AJbdVTZWwWlBLmT)** ([raw file](https://github.com/denigma/plasmid-bank/blob/cc896bd1822f29b9fb490e2469b3aa17370b9178/backend/src/main/scala/club/diybio/bank/domain/BananaPlasmidVectorRepository.scala#L143)):</sup>
Вот что мне фаундер бигдаты в своё время написал:

Yes, bigdata has different transaction semantics from openrdf. Openrdf assumes that writers do not conflict and all transactions are read/write connections. Bigdata has read-only transactions that provide light weight snapshot isolation and allow you to read against any visible commit point. The highest write throughput is through the unisolated connection.
Read-only connection creation is very cheap in the standalone and HA replication cluster modes.
Do NOT hold open read-only connections. This will pin the commit point on which the connection reads and all subsequent commit points. That will cause the backing file to grow if you are concurrently writing on the database since it will not be able to release storage until you close those read-only transactions and un-pin the associated commit points.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/denigma/plasmid-bank/19)

**Comment by antonkulaga** [comment]
<sup>**[backend/src/main/scala/club/diybio/bank/domain/BananaPlasmidVectorRepository.scala, line 143 [r1]](https://reviewable.io:443/reviews/denigma/plasmid-bank/19#-JsU9AJbdVTZWwWlBLmT)** ([raw file](https://github.com/denigma/plasmid-bank/blob/cc896bd1822f29b9fb490e2469b3aa17370b9178/backend/src/main/scala/club/diybio/bank/domain/BananaPlasmidVectorRepository.scala#L143)):</sup>
также он подчеркнул "Connections should not be left open unless you are using them."

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/denigma/plasmid-bank/19)

**Comment by antonkulaga** [comment]
<sup>**[backend/src/main/scala/club/diybio/bank/domain/bank/BananaDepositorRepository.scala, line 13 [r1]](https://reviewable.io:443/reviews/denigma/plasmid-bank/19#-JsU9SKQ1UdYIj_3Nrkh)** ([raw file](https://github.com/denigma/plasmid-bank/blob/cc896bd1822f29b9fb490e2469b3aa17370b9178/backend/src/main/scala/club/diybio/bank/domain/bank/BananaDepositorRepository.scala#L13)):</sup>
Ну, автор бигдаты говорил "Connections should not be left open unless you are using them." Я это понял как "сделал работу - закрыл коннекшин", когда в следующий раз понадобилось - открыл новый.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/denigma/plasmid-bank/19)

**Comment by antonkulaga** [comment]
<sup>**[backend/src/main/scala/club/diybio/bank/utils/sparql/QuerySyntax.scala, line 3 [r1]](https://reviewable.io:443/reviews/denigma/plasmid-bank/19#-JsU9nYfAJ0-UBJj5iP-)** ([raw file](https://github.com/denigma/plasmid-bank/blob/cc896bd1822f29b9fb490e2469b3aa17370b9178/backend/src/main/scala/club/diybio/bank/utils/sparql/QuerySyntax.scala#L3)):</sup>
как бы да, только куда именно?  DSL штука универсальная, делать что ли ветку бананы под это? Тогда надо делать бранч бананы, наследуемый от бигдатного (там как там до мёрджа дохре-похрен работы, ибо народ придиристый, требует разные мелочи фиксить)

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/denigma/plasmid-bank/19)

**Comment by antonkulaga** [comment]
<sup>**[project/Dependencies.scala, line 56 [r1]](https://reviewable.io:443/reviews/denigma/plasmid-bank/19#-JsUADVeQb_ap0xhiuzS)** ([raw file](https://github.com/denigma/plasmid-bank/blob/cc896bd1822f29b9fb490e2469b3aa17370b9178/project/Dependencies.scala#L56)):</sup>
какой-то "dependency leak" образовался в банане, тянутся тестовые депенденси из репа Алистера, решил заблочить это, так как они вообще не используются

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/denigma/plasmid-bank/19)

**Comment by rmihael** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[backend/src/main/scala/club/diybio/bank/domain/BananaPlasmidVectorRepository.scala, line 143 [r1]](https://reviewable.io:443/reviews/denigma/plasmid-bank/19#-JsU9AJbdVTZWwWlBLmT)** ([raw file](https://github.com/denigma/plasmid-bank/blob/cc896bd1822f29b9fb490e2469b3aa17370b9178/backend/src/main/scala/club/diybio/bank/domain/BananaPlasmidVectorRepository.scala#L143)):</sup>
Тогда надо их как-то закрывать? Или рассчитываем на сборщик мусора?

---

<sup>**[backend/src/main/scala/club/diybio/bank/domain/bank/BananaDepositorRepository.scala, line 13 [r1]](https://reviewable.io:443/reviews/denigma/plasmid-bank/19#-JsU9SKQ1UdYIj_3Nrkh)** ([raw file](https://github.com/denigma/plasmid-bank/blob/cc896bd1822f29b9fb490e2469b3aa17370b9178/backend/src/main/scala/club/diybio/bank/domain/bank/BananaDepositorRepository.scala#L13)):</sup>
ок, понятно

---

<sup>**[backend/src/main/scala/club/diybio/bank/utils/sparql/QuerySyntax.scala, line 3 [r1]](https://reviewable.io:443/reviews/denigma/plasmid-bank/19#-JsU9nYfAJ0-UBJj5iP-)** ([raw file](https://github.com/denigma/plasmid-bank/blob/cc896bd1822f29b9fb490e2469b3aa17370b9178/backend/src/main/scala/club/diybio/bank/utils/sparql/QuerySyntax.scala#L3)):</sup>
сделай бранч в нашем проекте, зачем заранее обобщать? Если допилим до юзабельного состояния -- можно будет думать о вливании куда-то ещё.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/denigma/plasmid-bank/19)

**Comment by antonkulaga** [comment]
<sup>**[backend/src/main/scala/club/diybio/bank/domain/BananaPlasmidVectorRepository.scala, line 143 [r1]](https://reviewable.io:443/reviews/denigma/plasmid-bank/19#-JsU9AJbdVTZWwWlBLmT)** ([raw file](https://github.com/denigma/plasmid-bank/blob/cc896bd1822f29b9fb490e2469b3aa17370b9178/backend/src/main/scala/club/diybio/bank/domain/BananaPlasmidVectorRepository.scala#L143)):</sup>
Честно говоря, я всандалил закрытие коннекшина внутрь трансакционного кода, а трансакции везде внутри реализации использую (можешь глянуть бигдатный бранч у меня в репе). Но, сейчас думаю, может стоит таки не закрывать их в трансакции, а сделать так, чтобы уже девелопер решал где их закрыть

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/denigma/plasmid-bank/19)

**Comment by rmihael** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[backend/src/main/scala/club/diybio/bank/domain/BananaPlasmidVectorRepository.scala, line 143 [r1]](https://reviewable.io:443/reviews/denigma/plasmid-bank/19#-JsU9AJbdVTZWwWlBLmT)** ([raw file](https://github.com/denigma/plasmid-bank/blob/cc896bd1822f29b9fb490e2469b3aa17370b9178/backend/src/main/scala/club/diybio/bank/domain/BananaPlasmidVectorRepository.scala#L143)):</sup>
Надо мне разобраться, что там вообще с транзакциями. Может подскажешь, где хорошо в скале сделаны SQL-ные транзакции, что бы я с подходами на знакомой почве разобрался?

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/denigma/plasmid-bank/19)

**Comment by antonkulaga** [comment]
<sup>**[backend/src/main/scala/club/diybio/bank/domain/BananaPlasmidVectorRepository.scala, line 143 [r1]](https://reviewable.io:443/reviews/denigma/plasmid-bank/19#-JsU9AJbdVTZWwWlBLmT)** ([raw file](https://github.com/denigma/plasmid-bank/blob/cc896bd1822f29b9fb490e2469b3aa17370b9178/backend/src/main/scala/club/diybio/bank/domain/BananaPlasmidVectorRepository.scala#L143)):</sup>
Ну, по-хорошему, должно быть понятие сессии. В Банане есть трейт для трасакций но нет (пока что трейта для сессий), но возможно скоро народ добавит, по крайней мере @InTheNow явно выссказался за идею ввести понятие сессии.  В случае с наличием сессии как правило, коннекшин открывается в начале сессии и закрывается в её конце. При наличии сессии в трасакциях коннекшины не закрываются (это я неправильно сделал, что закрываю их, нужно поправить будет). По SQL-у самые популярные это Slick и Activate Как обстоят дела с трансакциями в семантиквебных БДшках зависит от самих бдшек

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/denigma/plasmid-bank/19)

**Pull request merged**
